version: '3.7'
services:
  server:
    build:
      context: .
      target: development
    hostname: server
    container_name: server
    depends_on:
      - redis
    environment:
      - NODE_ENV=development
      - PORT=3000
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - GITHUB_API_TOKEN=351b1b95793f9c3cf71af0540b0c147aa6e08e36
    command: npm run start:dev
    volumes:
      - .:/usr/src/app/
      # - /usr/src/app/node_modules
    links:
      - redis
    ports:
      - "3000:3000"

  worker:
    build:
      context: .
      dockerfile: worker.DOCKERFILE
    environment:
      - NODE_ENV=development
      - PORT=3000
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - NEO4J_URL=bolt://neo4j:neo4j@localhost:7687
      - M2_HOME="C:/Program Files/apache-maven-3.6.3"
      - JP2G_JAR="./jp2g/java-parse-to-graph-1.0-SNAPSHOT.jar"
    # command: "sh -c 'node /app/build/worker.js'"
    depends_on: 
      - redis
      - neo4j
      - server

  redis:
    container_name: redis
    image: redis:4.0.14-alpine
    expose:
      - "6379"
  
  neo4j:
    container_name: neo4j
    image: neo4j:4.0
    ports:
      - "7687:7687"
      - "7474:7474"
      - "7473:7473"
    volumes:
      - $HOME/neo4j/data:/data
      - $HOME/neo4j/logs:/logs

  # bull-board:
  #   image: jondum/bull-board:latest
  #   container_name: bull-board
  #   depends_on: 
  #     - redis
  #     - server
  #   environment:
  #     - REDIS_HOST=redis://redis
  #     - PORT=3020
  #   ports:
  #     - "3020:3020"

  # bull-board:
  #   image: tombh/bull-board:latest
  #   container_name: bull-board
  #   depends_on: 
  #     - redis
  #     - server
  #   environment:
  #     - REDIS_HOST=redis
  #     - PORT=3020
  #   ports:
  #     - "3020:3000"