version: '3.7'
services:
  server:
    build:
      context: .
      target: development
    hostname: server
    container_name: server
    depends_on:
      - redis
    environment:
      - NODE_ENV=development
      - PORT=3000
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    command: npm run start:dev
    volumes:
      - .:/usr/src/app/
      - /usr/src/app/node_modules
    links:
      - redis
    ports:
      - "3000:3000"

  # worker:
  #   build:
  #     context: .
  #     dockerfile: worker.DOCKERFILE
  #   environment:
  #     - NODE_ENV=development
  #     - PORT=3000
  #     - REDIS_URL=redis
  #   # command: "sh -c 'node /app/build/worker.js'"
  #   depends_on: 
  #     - redis

  redis:
    image: redis:4.0.14-alpine
    container_name: redis
    expose:
      - "6379"

  # bull-board:
  #   image: jondum/bull-board:latest
  #   container_name: bull-board
  #   depends_on: 
  #     - redis
  #     - server
  #   environment:
  #     - REDIS_HOST=redis://redis
  #     - PORT=3020
  #   ports:
  #     - "3020:3020"

  # bull-board:
  #   image: tombh/bull-board:latest
  #   container_name: bull-board
  #   depends_on: 
  #     - redis
  #     - server
  #   environment:
  #     - REDIS_HOST=redis
  #     - PORT=3020
  #   ports:
  #     - "3020:3000"